Models/EmployeesDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Employees.Models
{
    public class EmployeesDbContext : DbContext
    {
        public EmployeesDbContext(DbContextOptions<EmployeesDbContext> options) : base(options)
        { 

        }
        public DbSet<Oddeli> Oddeli { get; set; }
        public DbSet<Vraboteni> Vraboteni { get; set;}
    }
}

Models/ErrorViewModel.cs
namespace Employees.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Oddeli.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employees.Models
{
    public class Oddeli
    {
        [Key]
        public int OddelId { get; set; }
        [Column(TypeName = "nvarchar(30)")]
        [DisplayName("Ime na oddel")]
        public string ImeOddel { get; set; }
        [DisplayName("Broj na vraboteni")]
        public int BrojVraboteni { get; set; }

    }
}

Models/Vraboteni.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employees.Models
{
    public class Vraboteni
    {
        [Key]
        public int VrabotenId { get; set; }
        [Column(TypeName ="nvarchar(30)")]
        public string Ime { get;set; }
        [Column(TypeName = "nvarchar(30)")]
        public string Prezime { get; set; }
        public decimal Plata { get; set; }
        [DisplayName("Oddel")]
        public int OddelId { get; set; }
    }
}

Controllers/HomeController.cs
using Employees.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Employees.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OddeliController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Employees.Models;

namespace Employees.Controllers
{
    public class OddeliController : Controller
    {
        private readonly EmployeesDbContext _context;

        public OddeliController(EmployeesDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Oddeli.ToListAsync());
        }

        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Oddeli());
            else
                return View(_context.Oddeli.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("OddelId,ImeOddel,BrojVraboteni")] Oddeli oddel)
        {
            if (ModelState.IsValid)
            {
                if (oddel.OddelId == 0)
                    _context.Add(oddel);
                else
                    _context.Update(oddel);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(oddel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var oddel = await _context.Oddeli.FindAsync(id);
            _context.Oddeli.Remove(oddel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/VraboteniController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Employees.Models;

namespace Employees.Controllers
{
    public class VraboteniController : Controller
    {
        private readonly EmployeesDbContext _context;

        public VraboteniController(EmployeesDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Vraboteni.ToListAsync());
        }

        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Vraboteni());
            else
                return View(_context.Vraboteni.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("VrabotenId,Ime,Prezime,Plata,OddelId")] Vraboteni vraboten)
        {
            if (ModelState.IsValid)
            {
                if (vraboten.VrabotenId == 0)
                    _context.Add(vraboten);
                else
                    _context.Update(vraboten);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vraboten);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vraboten = await _context.Vraboteni.FindAsync(id);
            _context.Vraboteni.Remove(vraboten);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Oddeli/AddOrEdit.cshtml
@model Employees.Models.Oddeli
@{
    ViewData["Title"] = "Оддели";
}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>Оддели</h1>
        <form asp-action="AddOrEdit" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OddelId" />
            <div class="form-group">
                <label asp-for="ImeOddel" class="control-label"></label>
                <input asp-for="ImeOddel" class="form-control" />
                <span asp-validation-for="ImeOddel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrojVraboteni" class="control-label"></label>
                <input asp-for="BrojVraboteni" class="form-control" />
                <span asp-validation-for="BrojVraboteni" class="text-danger"></span>
            </div>

            <div class="row mt-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Внеси" class="btn btn-primary w-100" />
                    </div>
                </div>
                <div class="col-md-6">
                    <a asp-action="Index" class="btn btn-secondary  w-100">Преглед</a>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Oddeli/Index.cshtml
@model IEnumerable<Employees.Models.Oddeli>
@{
    ViewData["Title"] = "Index";
}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h1>Оддели</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ImeOddel)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BrojVraboteni)
                    </th>
                    <th>
                        <a asp-action="AddOrEdit" class="btn btn-sm btn-success">
                            <i class="fa-solid fa-plus"></i> New
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ImeOddel)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BrojVraboteni)
                        </td>
                        <td>
                            <form asp-action="Delete" asp-route-id="@item.OddelId">
                                <div class="btn-group btn-group-sm">
                                    <a asp-action="AddOrEdit" asp-route-id="@item.OddelId" class="btn btn-warning">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <button type="submit" class="btn btn-danger"
                                        onclick="return confirm('Дали сакаш да го избришиш овој запис ?')">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employees</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employees.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employees</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Oddeli" asp-action="Index">Oddeli</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vraboteni" asp-action="Index">Vraboteni</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Employees - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Vraboteni/AddOrEdit.cshtml
@model Employees.Models.Vraboteni

@{
    ViewData["Title"] = "Вработени";
}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form asp-action="AddOrEdit" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VrabotenId" />
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Plata" class="control-label"></label>
                        <input asp-for="Plata" class="form-control" />
                        <span asp-validation-for="Plata" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="OddelId" class="control-label"></label>
                        <input asp-for="OddelId" class="form-control" />
                        <span asp-validation-for="OddelId" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row mt-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Внеси" class="btn btn-primary w-100" />
                    </div>
                </div>
                <div class="col-md-6">
                    <a asp-action="Index" class="btn btn-secondary  w-100">Преглед</a>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Vraboteni/Index.cshtml
@model IEnumerable<Employees.Models.Vraboteni>

@{
    ViewData["Title"] = "Index";
}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h1>Вработени</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Ime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Prezime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Plata)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.OddelId)
                    </th>

                    <th>
                        <a asp-action="AddOrEdit" class="btn btn-sm btn-success">
                            <i class="fa-solid fa-plus"></i> New
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Prezime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Plata)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OddelId)
                        </td>
                        <td>
                            <form asp-action="Delete" asp-route-id="@item.VrabotenId">
                                <div class="btn-group btn-group-sm">
                                    <a asp-action="AddOrEdit" asp-route-id="@item.VrabotenId" class="btn btn-warning">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <button type="submit" class="btn btn-danger"
                                        onclick="return confirm('Дали сакаш да го избришиш овој запис ?')">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>